name: Meu primeiro workflow

on:
  push:
    branches:
      - main

jobs:
  primeiro_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello, Github Actions!
        run: echo "Hello, Github Actions!"

      - name: Qual o diretório atual?
        run: pwd

      - name: Qual o conteúdo do diretório atual?
        run: ls -a

      - name: Até mais
        run: echo "See you, boyyy"

